### ISSUE TITLE
"npm run install" fails

### ISSUE THREAD

**Issue by CaliLuke** [angineering/FullStackTemplate#1]
I'm trying to follow your tutorial but I got stuck midway when you add the App.jsx... so I decided to clone you repo instead but I quickly run into a problem:

`$ npm run install`

produces the following output for me:

```
lucas-mbp:static luca$ npm run install
npm ERR! missing script: install

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/luca/.npm/_logs/2017-09-10T20_33_01_743Z-debug.log
```

What am I doing wrong?

**Comment by metandPRO** [comment]
With `$ npm run script` you are able to run one of the custom commands defined in the package.json file under the "scripts" field:
```javascript
"scripts": {
    "build": "webpack -p --progress --config webpack.config.js",
    "dev-build": "webpack --progress -d --config webpack.config.js",
    "test": "echo \"Error: no test specified\" && exit 1",
    "watch": "webpack --progress -d --config webpack.config.js --watch"
}
```
What I assume you want to do is simply: `$ npm install` in the static folder. This will install including all dependencies. Right?

run command: [https://docs.npmjs.com/cli/run-script](url)
install command: [https://docs.npmjs.com/cli/install](url)

**Comment by vinodrajendran001** [comment]
I cloned the "simple website" repository and followed all the steps as mentioned in README. But, the website is not loading.

npm run watch - runs till 64 % and the last message is this

 64% building modules 453/454 modules 1 active ...ack_template/static/css/fullstack.css(node:11878) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
Hash: 9067f5fc162232cd71f4                    
Version: webpack 3.9.1
Time: 4004ms
                               Asset       Size  Chunks                    Chunk Names
1776662db43bd611e4eb11d2add6d1c6.jpg    1.24 MB          [emitted]  [big]  
                           bundle.js    4.66 MB       0  [emitted]  [big]  main
                          styles.css  522 bytes       0  [emitted]         main
 [205] ./js/index.jsx 470 bytes {0} [built]
 [305] ./js/App.jsx 3.02 kB {0} [built]
 [306] ./js/Hello.jsx 4.23 kB {0} [built]
 [447] ./images/header.jpg 82 bytes {0} [built]
 [448] ./css/fullstack.css 41 bytes {0} [built]
 [449] ./node_modules/css-loader!./css/fullstack.css 714 bytes [built]
    + 447 hidden modules
Child extract-text-webpack-plugin:
     1 asset
       [0] ./node_modules/css-loader!./css/fullstack.css 714 bytes {0} [built]
       [2] ./images/header.jpg 82 bytes {0} [built]
        + 1 hidden module

After running python server.py, the local host page is blank nothing is loaded.

Am I missing something?

**Comment by angineering** [comment]
The documentation has been updated to reflect that it should be "npm install"
